# Generated by Django 4.2.1 on 2023-06-23 06:34

import cloudinary_storage.storage
import cloudinary_storage.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='post_video/%Y-%m-%d/', validators=[cloudinary_storage.validators.validate_video]),
        ),
    ]
