# Generated by Django 4.2.1 on 2023-05-06 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coverimage',
            name='coverimage',
            field=models.ImageField(default='cover_images/placeholder.jpg', upload_to='cover_images/%Y-%m-%d/'),
        ),
        migrations.AlterField(
            model_name='profileimage',
            name='profileimage',
            field=models.ImageField(default='profile_images/placeholder.jpg', upload_to='profile_images/%Y-%m-%d/'),
        ),
    ]
