# Generated by Django 4.2.1 on 2023-05-06 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_coverimage_coverimage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coverimage',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='profileimage',
            options={'ordering': ('-created',)},
        ),
        migrations.RenameField(
            model_name='coverimage',
            old_name='coverimage',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='profileimage',
            old_name='profileimage',
            new_name='image',
        ),
    ]
