# Generated by Django 4.2.1 on 2023-06-02 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatImageFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='chat_images/%Y-%m-%d')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('frame', models.ForeignKey(on_delete=models.Model, to='chats.chatimageframe')),
            ],
        ),
    ]
