# Generated by Django 4.2.1 on 2023-06-02 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_chatimageframe_chatimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatimageframe',
            name='thread',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='chats.thread'),
            preserve_default=False,
        ),
    ]
