# Generated by Django 3.2.20 on 2023-11-06 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('about', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('admin_members', models.ManyToManyField(related_name='_groups_customgroup_admin_members_+', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(related_name='group', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='GroupProfileImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='group_profile_images/placeholder.png', upload_to='group_profile_images/%Y-%m-%d/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.customgroup')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
