# Generated by Django 4.2.1 on 2023-06-02 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_groupprofileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupprofileimage',
            name='image',
            field=models.ImageField(default='group_profile_images/placeholder.png', upload_to='group_profile_images/%Y-%m-%d/'),
        ),
    ]
